baseURL: https://benjaminporter.me
languageCode: en-us
title: Benjamin Porter

params:
  tagline:
    - Software Engineer
    - Terraform Engineer
    - YAML Engineer
  emoji:
    - 🍓
    - 🌮
    - 🎻
    - 🐈

enableGitInfo: true

disableKinds:
  - taxonomy
  - taxonomyTerm
