baseURL: https://benjaminporter.me
languageCode: en-us
title: Benjamin Porter

params:
  tagline:
    - Software Engineer at Affirm
    - Terraform Writer at Affirm

enableGitInfo: true

disableKinds:
  - taxonomy
  - taxonomyTerm
